### ISSUE TITLE
`remind101/conveyor` docker image is unavailable

### ISSUE THREAD

**Issue by jayzes** [remind101/conveyor#21]
Looks like `remind101/conveyor` isn't available on Docker Hub, which makes the Cloudformation template fail. Is it in a different location now, or just not made public?

**Comment by jayzes** [comment]
Poking around a bit more - `remind101/conveyor-builder` is in the same boat

**Comment by ejholmes** [comment]
Woops. I've just made these public on docker hub. Thanks!
