### ISSUE TITLE
Successful/Failed build notifications

### ISSUE THREAD

**Issue by russ** [remind101/conveyor#29]
It would be a really nice feature to be able to add a web hook to notify something like a slack channel that a build succeeded or failed. Right now I'm just checking s3 for the new log files manually. If there is already an easier way I'd love to hear it.

I tried to start working on this locally but I can't get everything to play nicely together. Are the docs on getting this running locally up to date? If I can get this running I will start working on it.

Thanks for the great work on this and empire btw.

**Comment by ejholmes** [comment]
I just merged https://github.com/remind101/conveyor/pull/30 which has some better instructions for bootstrap in dev and running the tests. Let me know if that helps!

I started on a branch that would add an events system [here](https://github.com/remind101/conveyor/compare/events) and we could provide various implementations for event handling (e.g. Slack). I didn't go very far with it, but might be good for reference.
