### ISSUE TITLE
conveyor and conveyor-builder images out of sync?

### ISSUE THREAD

**Issue by cordoval** [remind101/conveyor#47]
i see https://hub.docker.com/r/remind101/conveyor/tags/ and https://hub.docker.com/r/remind101/conveyor-builder/tags/ but it is 4 months ago as opposed to the conveyor image which is hours old.  Are you triggering this manually or is also setup automatically like the conveyor image?

**Comment by cordoval** [comment]
related https://github.com/remind101/conveyor/pull/45

**Comment by ejholmes** [comment]
Yeah. The image for remind101/conveyor-builder is built manually right now.

**Comment by cordoval** [comment]
oh good to know, thanks
