### ISSUE TITLE
Update Docker to More Recent Version

### ISSUE THREAD

**Issue by Caleb-An** [remind101/conveyor#75]
Every once in a while, a build fails with `Layer already being pulled by another client. Waiting.`. [This issue](https://github.com/moby/moby/issues/15603) was supposedly fixed on [1.9](https://github.com/moby/moby/pull/15489). 

Are there any plans to move towards newer Docker Engine versions? I know Docker's not the most stable, so it'd definitely be a slow process. Let me know if you'd like help with it.

**Comment by ejholmes** [comment]
This would be good, but I'm gonna go ahead and close this and move it over to https://github.com/remind101/conveyor-builder/issues/5, since that's where the Docker version is specified.
